//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/server/robbery/ActiveTrapRes.proto
namespace com.sy599.guaji3d.message.packet.protoPacket
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActiveTrapResMsg")]
  public partial class ActiveTrapResMsg : global::ProtoBuf.IExtensible
  {
    public ActiveTrapResMsg() {}
    
    private long _signalId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"signalId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long signalId
    {
      get { return _signalId; }
      set { _signalId = value; }
    }
    private int _trapId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"trapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int trapId
    {
      get { return _trapId; }
      set { _trapId = value; }
    }
    private int _code;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }

    private int _type = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _params = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"params", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> @params
    {
      get { return _params; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _targetIds = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(6, Name=@"targetIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> targetIds
    {
      get { return _targetIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}